export const trovePilotEngineAbi = [
  {
    type: 'function',
    name: 'jobId',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'uint256' }],
  },
  {
    type: 'function',
    name: 'TROVE_MANAGER',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'MUSD',
    stateMutability: 'view',
    inputs: [],
    outputs: [{ name: '', type: 'address' }],
  },
  {
    type: 'function',
    name: 'redeemHintedTo',
    stateMutability: 'nonpayable',
    inputs: [
      { name: '_musdAmount', type: 'uint256' },
      { name: '_recipient', type: 'address' },
      { name: '_firstHint', type: 'address' },
      { name: '_upperHint', type: 'address' },
      { name: '_lowerHint', type: 'address' },
      { name: '_partialNICR', type: 'uint256' },
      { name: '_maxIter', type: 'uint256' },
    ],
    outputs: [],
  },
  {
    type: 'event',
    name: 'RedemptionExecuted',
    inputs: [
      { name: 'jobId', type: 'uint256', indexed: true },
      { name: 'caller', type: 'address', indexed: true },
      { name: 'recipient', type: 'address', indexed: true },
      { name: 'musdRequested', type: 'uint256', indexed: false },
      { name: 'musdRedeemed', type: 'uint256', indexed: false },
      { name: 'musdRefunded', type: 'uint256', indexed: false },
      { name: 'collateralOut', type: 'uint256', indexed: false },
      { name: 'maxIter', type: 'uint256', indexed: false },
      { name: 'hinted', type: 'bool', indexed: false },
    ],
    anonymous: false,
  },
] as const;
